Repository ToucanToco/toucan-data-sdk, pull requests merged in 2018-08, with the labels that each got.

#56 Hotfix :: fix joblib changes
  setup.cfg
  tests/utils/test_helpers.py
  toucan_data_sdk/utils/decorators.py
  toucan_data_sdk/utils/helpers.py
Labels: bug

#55 Feature :: util groupby
  .gitignore
  tests/utils/postprocess/test_groupby.py
  toucan_data_sdk/utils/postprocess/__init__.py
  toucan_data_sdk/utils/postprocess/groupby.py
Labels: needs review

#62 Feature :: Retrieve output domain thanks to pagination
  tests/test_sdk.py
  toucan_data_sdk/sdk.py
Labels: enhancement, needs review
