Repository ToucanToco/toucan-data-sdk, pull requests merged in 2018-03, with the labels that each got.

#37 New util rank
  tests/utils/postprocess/test_rank.py
  toucan_data_sdk/utils/postprocess/__init__.py
  toucan_data_sdk/utils/postprocess/rank.py
Labels: enhancement

#39 Fix cache without small_app param
  example/model_augment.ipynb
  example/model_basemaps.ipynb
  setup.cfg
  tests/test_sdk.py
  toucan_data_sdk/sdk.py
Labels: Please review, bug

#40 Fix :: small app url for retrocompability
  example/model_basemaps.ipynb
  setup.cfg
  tests/test_sdk.py
  toucan_data_sdk/sdk.py
Labels: bug

#42 Hotfix :: sort instead of sort values
  setup.cfg
  tests/utils/postprocess/test_sort.py
  toucan_data_sdk/utils/postprocess/__init__.py
  toucan_data_sdk/utils/postprocess/sort.py
Labels: bug
