Repository ToucanToco/toucan-data-sdk, pull requests merged in 2018-10, with the labels that each got.

#70 Feature :: add traceback + clean notebooks
  Makefile
  example/model_augment.ipynb
  example/model_basemaps.ipynb
  example/model_data_specs.ipynb
  example/model_debug.ipynb
  setup.cfg
  tests/fixtures/deleteme-exception.dump
  tests/test_sdk.py
  toucan_data_sdk/sdk.py
  toucan_data_sdk/utils/traceback.py
Labels: enhancement

#71 Feature :: add lib scipy
  setup.cfg
Labels: enhancement, needs review

#73 add change_date_format function
  tests/utils/postprocess/test_converter.py
  toucan_data_sdk/utils/helpers.py
  toucan_data_sdk/utils/postprocess/__init__.py
  toucan_data_sdk/utils/postprocess/converter.py
  toucan_data_sdk/utils/postprocess/math.py
  toucan_data_sdk/utils/traceback.py
Labels: Please review, needs review

#74 Switch param dst_column to new_column
  setup.cfg
  tests/utils/postprocess/test_converter.py
  tests/utils/postprocess/test_math.py
  tests/utils/postprocess/test_replace.py
  tests/utils/postprocess/test_text.py
  tests/utils/test_helpers.py
  toucan_data_sdk/utils/helpers.py
  toucan_data_sdk/utils/postprocess/converter.py
  toucan_data_sdk/utils/postprocess/math.py
  toucan_data_sdk/utils/postprocess/replace.py
  toucan_data_sdk/utils/postprocess/text.py
Labels: Please review

#76 f/add-argmin function
  tests/utils/postprocess/test_argmax.py
  toucan_data_sdk/utils/postprocess/__init__.py
  toucan_data_sdk/utils/postprocess/argmax.py
Labels: enhancement
