Repository ToucanToco/toucan-data-sdk, pull requests merged in 2018-04, with the labels that each got.

#44 Feature :: waterfall without insideGroup
  setup.cfg
  tests/utils/postprocess/test_waterfall.py
  tests/utils/test_decorators_cache.py
  toucan_data_sdk/utils/postprocess/waterfall.py
  tox.ini
Labels: enhancement, needs review

#43 feature :: top_group
  tests/utils/postprocess/test_top.py
  toucan_data_sdk/utils/postprocess/__init__.py
  toucan_data_sdk/utils/postprocess/top.py
Labels: WIP

#45 Fix :: typo agregate -> aggregate
  Makefile
  setup.cfg
  tests/test_sdk.py
  tests/utils/postprocess/test_melt.py
  tests/utils/postprocess/test_top.py
  tests/utils/test_data_specs.py
  tests/utils/test_helpers.py
  toucan_data_sdk/utils/generic/compute_cumsum.py
  toucan_data_sdk/utils/generic/compute_ffill_by_group.py
  toucan_data_sdk/utils/postprocess/query_df.py
  toucan_data_sdk/utils/postprocess/rename.py
  toucan_data_sdk/utils/postprocess/replace.py
  toucan_data_sdk/utils/postprocess/top.py
  tox.ini
Labels: bug
