Repository ToucanToco/toucan-data-sdk, pull requests merged in 2019-08, with the labels that each got.

#29 Concat integer columns without trailing .0
  tests/utils/postprocess/test_text.py
  toucan_data_sdk/utils/postprocess/text.py
Labels: enhancement, need review

#30 Feature :: new postprocess `if_else`
  tests/utils/postprocess/test_if_else.py
  toucan_data_sdk/utils/postprocess/if_else.py
Labels: enhancement, need review

#31 Feature :: top :: support date strings
  tests/utils/postprocess/test_top.py
  toucan_data_sdk/utils/postprocess/top.py
Labels: enhancement, need review

#32 Fix :: expose if_else + fix signature
  setup.cfg
  tests/utils/postprocess/test_if_else.py
  toucan_data_sdk/utils/postprocess/__init__.py
  toucan_data_sdk/utils/postprocess/if_else.py
Labels: bug, need review

#33 Feature :: add the possibility to pivot only a subset of value
  tests/utils/postprocess/test_pivot.py
  toucan_data_sdk/utils/postprocess/pivot.py
Labels: enhancement, postprocess

#35 Fix :: avoid mutating dataframe in `pivot_by_group`
  tests/utils/postprocess/test_pivot.py
  tests/utils/test_helpers.py
  toucan_data_sdk/utils/helpers.py
  toucan_data_sdk/utils/postprocess/pivot.py
  toucan_data_sdk/utils/postprocess/top.py
Labels: bug, need review
